name: Update JSON Index - file listing all files in 'json' folder

on:
  workflow_dispatch: # This makes the workflow manual trigger only
  #push:
    #paths:
      #- 'json/**' # run only when changes in folder json

jobs:
  update-json-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Generate JSON file if changes detected
        run: |
          echo "Generating JSON index..."
          files=$(ls json | jq -R -s 'split("\n") | map(select(. != ""))')
          echo "$files" | jq '.' > index.json
          git add -f index.json

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Github Action - Update JSON index
